R-ArcGIS/arcgislayers

R/add_item.R

Thanks for creating and maintaining this package! I suspect my team will be making future use of it. In any case, I was having trouble publishing a layer and getting a cryptic R message when the problem was actually a permissions issue. Calling `detect_errors()` before returning the response as a data frame surfaced the issue earlier.

call detect_errors on the response earlier

---

R/arc-add-update-delete.R
R/utils.R

This PR fixes the use of `prapre_spatial_filter()` in `delete_features()`.
A new utility function `coalesce_crs()` has been added to return the frist non-missing CRS object as well.

Fixes the use of prepare_spatial_filter() in delete_features()

---

R/arc-select.R
tests/testthat/test-arc-select-respect-crs.R

`collect_layer()` was properly processing the CRS via `parse_esri_json()`. Then, after combining results, the CRS was being manually set to that of the `FeatureLayer` which was incorrect when the `crs` argument is provided. This PR only set the CRS to the result when it is missing 
Adds a test to check for this condition in the future.
https://github.com/R-ArcGIS/arcgislayers/issues/94
CC @elipousson

Respect CRS in `arc_select()` 

---

DESCRIPTION
R/arc-add-update-delete.R
R/arc-select.R
R/dev-notes.R

This bumps the required version of httr2 to 1.0.0. It was announced for GA this week and the function multi_req_perform was renamed. Which is a breaking change.
https://github.com/R-ArcGIS/arcgislayers/issues/93

bump to version 1.0.0 of httr2

---

NEWS.md
R/arc-add-update-delete.R
R/arc-raster.R
R/create-service.R
R/utils-feature-server.R
R/utils-spatial-filter.R
R/utils.R
man/arc_raster.Rd
man/create_feature_server.Rd
man/get_layer.Rd
man/modify.Rd
man/spatial_filter.Rd
man/utils.Rd

- [✅] update NEWS.md
- [✅] documentation updated with `devtools::document()`
- [ ? ] `devtools::check()` passes locally
Got 2 errors ✖ | 4 warnings ✖ | 2 notes ✖ with `devtools::check()`.
Your example badges were included in the details section of the docs. Some functions - like `arc_raster()` - lacked details. In that case, I added a details section. 
Closes: https://github.com/R-ArcGIS/arcgislayers/issues/85
Found this when I ran `check()`: https://github.com/R-ArcGIS/arcgislayers/issues/102
Got this error running examples: Error in coalesce_crs(x, y) : could not find function "coalesce_crs"
In the tests: Error in `expect_fals("sf" %in% class(res))`: could not find function "expect_fals"

add lifecycle badges to exported functions #85

---

.github/workflows/R-CMD-check.yaml
README.Rmd
README.md

Adds a new github action to run r cmd check on mac, windows, and linux. It also adds a check badge to the readme 
Closes https://github.com/R-ArcGIS/arcgislayers/issues/30
Pray to any god you may believe in and hope that the package passes R CMD check

update readme to have rcmd check and add rcmd check GHA

---

R/dplyr-features.R

select() method should be case insensitive as this is the case for the rest endpoint. This PR makes select not case sensitv.
This is dependent upon a fix in arcgisutils which should be reinstalled.

Make select() not case sensitive

---

R/arc-open.R
R/print-methods.R
tests/testthat/test-arc_open.R
tests/testthat/test-arc_select.R
tests/testthat/test-return-geometry.R

Removes the attribute n from Tables and FeatureLayers as well as adjusts their print methods. Updates some tests as well which were lazily written
Closes https://github.com/R-ArcGIS/arcgislayers/issues/121

remove n from attributes and print method. update tests

---

DESCRIPTION
NEWS.md
R/add_item.R
R/arc-add-update-delete.R
R/arc-open.R
R/arc-raster.R
R/arc-read.R
R/arc-select.R
R/create-service.R
R/get-estimates.R
R/truncate.R
R/utils-feature-server.R
man/arc_open.Rd
man/arc_raster.Rd
man/arc_read.Rd
man/arc_select.Rd
man/create_feature_server.Rd
man/get_layer.Rd
man/get_layer_estimates.Rd
man/modify.Rd
man/publish.Rd
man/truncate_layer.Rd

When "ARCGIS_TOKEN" is an empty string, it will sometimes cause HTTP 498 "invalid token" error. Need to NULL the empty string to handle this. 
No issue opened here. See https://github.com/R-ArcGIS/arcgisutils/issues/5.
Waiting for https://github.com/R-ArcGIS/arcgisutils/pull/6 to be merged first.

use arc_token() to handle empty tokens

---

NEWS.md
R/add_item.R
R/create-service.R
man/create_feature_server.Rd
man/publish.Rd

This PR removes the `user` arguments from publishing functions. The user is now fetched from the auth token.

remove user argument. Use arcgisutils check_token_has_user()

---

NEWS.md
R/arc-select.R
man/arc_select.Rd
tests/testthat/test-arc_select.R

This PR adds a `page_size` argument to `arc_select()` which permits us to have more control over the total number of features that are returned on a per-request basis. This will allow us to overcome the issue of timeouts with dense geometries. 
- closes https://github.com/R-ArcGIS/arcgislayers/issues/141
- Create docs on working with dense geometries. This doc will tell users how to utilize the `batch_size` argument to increase the number of requests made and reduce the number of features per page.

Add `page_size` argument to `arc_select()`

---

R/utils-feature-server.R
tests/testthat/_snaps/get-layers.md
tests/testthat/test-get-layers.R

This PR fixes a bug where `get_layers()` would not work on `Table`s in a `FeatureServer`
closes https://github.com/R-ArcGIS/arcgislayers/issues/147

fix: get_layers() did not work on tables

---

NEWS.md
R/arc-open.R
tests/testthat/test-arc_open.R

Per request of @elipousson, remove `compact()` around `fetch_layer_metadata()` so that all properties, including NULL ones, are returned from `arc_open()`. 
``` r
library(arcgislayers)
"https://geodata.md.gov/imap/rest/services/Transportation/MD_Transit/FeatureServer/1" |> 
arc_open() |> 
length()
#> [1] 56
"https://geodata.md.gov/imap/rest/services/Transportation/MD_Transit/FeatureServer/9" |> 
arc_open() |> 
length()
#> [1] 56
```

remove compact() from arc_open()

---

NEWS.md
R/arc-raster.R

This modifies `arc_raster()` so that the result of `/exportImage` is downloaded into a temporary file fixing issues where the url would expire after connecting to it.

fix arc_raster

---

NEWS.md
R/arc-select.R
R/sf-methods.R

- [-] `devtools::check()` passes locally
Fixes  #191 by adding a helper function (`get_query_resps()`) that handles layers that don't support pagination by using a standard query request.
Also fixes the CRS bug #188 using a similar approach as the esri2sf package.
Fix #191 and #188
None identified.

Fix #191 and #188

---

R/attachments.R
dev/attachments-demo.R

Describe the changes to the repository. What is being added or removed? What design choices were made that should be reviewed?
Please link any issues that are closed by this PR
Are there any follow up tasks to be addressed after this PR is merged?

Attachments

---

DESCRIPTION
NEWS.md
R/arc-select.R
tests/testthat/test-pbf.R

This PR adds `arcpbf` as a dependency and uses it to process responses when protocol buffers are a supported format. 
This results in a roughly 3x speed up for processing polygons and lines. The speed enhancement is much greater for points.

utilize arcpbf when possible add tests

---

NEWS.md
R/arc-open.R

If a layer type cannot be determined, `arc_open()` returns early and returns the raw list. 
https://github.com/R-ArcGIS/arcgislayers/issues/163

Closes #163

---

R/arc-select.R

Adds type checks to the arguments of `arc_select()` this should prevent any nasty errors later down. 
https://github.com/R-ArcGIS/arcgislayers/issues/181

arc_select() type checks 

---

DESCRIPTION
NEWS.md
R/arc-select.R
tests/testthat/test-page-size.R

This PR modifies the type checks use in `arc_select()` when `page_size` argument was passed.
There was no test to check that this feature worked which is why the change wasn't caught. 
This PR adds a test in addition to a fix.
#205

Bug fix: page_size was not respected 

---

R/attachments.R
man/arc_open.Rd
man/attachments.Rd
tests/testthat/test-attachments.R

This PR adds a new argument to `query_layer_attachments()` which makes returning metadata optional. 
This closes #208. This was problematic because the metadata provided from their attachments contains null string characters which are invalid in R.

Make attachment metadata optional

---

R/arc-select.R

This won't pass check due to unrelated errors but it fixes a new issue created by coercing NULL page_size values using `as.integer()`.

Fix error with `arc_select()` when `page_size = NULL` (fix #212)

---

R/arc-raster.R

This fixes a bug on windows reported here:  https://github.com/rspatial/terra/issues/1574
From `?donwload.file 
> Code written to download binary files must use mode = "wb" (or "ab"), but the problems incurred by a text transfer will only be seen on Windows.

use mode="wb" when downloading files

---

NEWS.md
R/arc-select.R

Add warning if the number of rows in results is less than the expected number of features.
https://github.com/R-ArcGIS/arcgislayers/issues/220
Identify what is causing this issue with the City of Baltimore server so the message can be a bit more specific about trouble-shooting.

Fix #220 by adding informative warning

---

NEWS.md
R/arc-open.R
R/utils.R
tests/testthat/test-arc_open.R

This is a little different than what you outlined in response to the issue I flagged with #215 but I figured a PR might be the easiest way to show what I had in mind. Basically, the API resource URLs on the standard ArcGIS Hub sites include default query arguments in the URL:
This PR adds utility functions to parse the query, ignore default values, and only retain custom values.
https://github.com/R-ArcGIS/arcgislayers/issues/215
Update documentation to show that custom query values are retained but default values are ignored.

Add helper functions to clear default query in URL (#215)

---

.Rbuildignore
DESCRIPTION
NEWS.md
R/zzz.R

- [] `devtools::check()` passes locally
This PR removes the dbplyr integration with arcgislayers. 
Closes #218 #111 #224 
--------
CC @elipousson will this affect you at all?

refactor: remove dbplyr and dplyr integration

---

NEWS.md
R/arc-select.R

Partly address #226 by passing appropriate value to `arg` parameter of `check_string()` when using `...` with `arc_select()`
The validation of `...` parameters could be improved overall. If `arc_select()` had a `call` argument that would also improve the handling of errors when `arc_select()` is inside of another function (like `arc_read()`).

Improve `arc_select()` error message per #226

---

R/utils.R

I used `encode_field_values()` with the `field` argument set this evening for the first time and caught what is (in retrospect) an obvious error in the arg_match call used by `list_field_domains()` to validate the input.
Fill in `field` as the `arg` parameter of `rlang::arg_match` within `list_field_domains()`.

Fill in missing arg for arg_match in `list_field_domains`

---

NEWS.md
R/utils-feature-server.R
man/get_layer.Rd
tests/testthat/test-get-all-layers.R
tests/testthat/test-get-layer.R
tests/testthat/test-get-layers.R

Add input checks for `get_layer`, `get_all_layers`, `get_layers` to require `FeatureServer`, `MapServer` or `GroupLayer` and avoid generic "subscript out of bounds" error message with invalid inputs. Also update docs to document support for GroupLayer input data and add tests for new input checks.
The new checks use the existing `check_inherits_any` helper function.
I can add an issue if needed - this seemed small so I wasn't sure a separate issue was required.
None that I can think of.

Add input checks for `get_layer` and related functions

---

tests/testthat/test-get-all-layers.R

Caught a tiny typo in https://github.com/R-ArcGIS/arcgislayers/pull/243

Fix typo in get_all_layers test

---

R/arc-read.R
tests/testthat/test-encode-field-values.R

I haven't been able to figure out entirely but better handling for NA values by `encode_field_values()` avoids the error at least (although there is now a warning).
Minor change to leave missing values for encoded field columns in place.
https://github.com/R-ArcGIS/arcgislayers/issues/237
https://github.com/R-ArcGIS/arcgislayers/issues/236

Improve handling of missing values for encoded fields
